import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { DocxService } from "../../src/services/docx/DocxService.js";
import { DocxTool } from "../../src/tools/DocxTool.js";

let tempDir: string;
let service: DocxService;
let tool: DocxTool;

before(async () => {
  tempDir = path.join(os.tmpdir(), `wordagent-docx-test-${Date.now()}`);
  await fs.mkdir(tempDir, { recursive: true });
  service = new DocxService();
  tool = new DocxTool();
});

after(async () => {
  try {
    await fs.rm(tempDir, { recursive: true, force: true });
  } catch {
    // Windows sometimes locks files
  }
});

describe("DocxService — generate", () => {
  it("should generate a simple .docx with paragraphs", async () => {
    const result = await service.generate({
      title: "Test Document",
      paragraphs: [
        { text: "Hello, World!", heading: "Heading1" },
        { text: "This is a test paragraph." },
        { text: "Another paragraph here." },
      ],
    });

    assert.ok(result.ok, "Generate should succeed");
    if (result.ok) {
      assert.ok(result.value.buffer.length > 0, "Buffer should not be empty");
      assert.ok(result.value.size > 0, "Size should be positive");
    }
  });

  it("should generate a .docx with headings", async () => {
    const result = await service.generate({
      paragraphs: [
        { text: "Document Title", heading: "Title" },
        { text: "Section 1", heading: "Heading1" },
        { text: "Subsection 1.1", heading: "Heading2" },
        { text: "Sub-subsection 1.1.1", heading: "Heading3" },
        { text: "Normal paragraph." },
      ],
    });

    assert.ok(result.ok, "Generate with headings should succeed");
    if (result.ok) {
      assert.ok(result.value.buffer.length > 0, "Buffer should not be empty");
    }
  });

  it("should generate a .docx with tables", async () => {
    const result = await service.generate({
      title: "Financial Report",
      paragraphs: [
        { text: "Revenue Summary", heading: "Heading1" },
      ],
      tables: [
        {
          rows: [
            ["Item", "Q1", "Q2", "Q3"],
            ["Revenue", "1,234,567", "1,500,000", "1,750,000"],
            ["Cost", "987,654", "1,100,000", "1,200,000"],
            ["Net", "246,913", "400,000", "550,000"],
          ],
          headerRow: true,
        },
      ],
    });

    assert.ok(result.ok, "Generate with table should succeed");
    if (result.ok) {
      assert.ok(result.value.buffer.length > 0, "Buffer should not be empty");
    }
  });

  it("should generate a .docx with bullet points", async () => {
    const result = await service.generate({
      paragraphs: [
        { text: "Key Findings", heading: "Heading1" },
        { text: "Revenue increased by 15%", bullet: true },
        { text: "Cost reduced by 8%", bullet: true },
        { text: "Net profit margin improved", bullet: true },
      ],
    });

    assert.ok(result.ok, "Generate with bullets should succeed");
    if (result.ok) {
      assert.ok(result.value.buffer.length > 0, "Buffer should not be empty");
    }
  });

  it("should generate a .docx with formatting (bold, italic, alignment)", async () => {
    const result = await service.generate({
      paragraphs: [
        { text: "Centered Title", heading: "Title", alignment: "center" },
        { text: "Bold paragraph", bold: true },
        { text: "Italic paragraph", italic: true },
        { text: "Right-aligned text", alignment: "right" },
        { text: "Large text", fontSize: 18 },
      ],
    });

    assert.ok(result.ok, "Generate with formatting should succeed");
    if (result.ok) {
      assert.ok(result.value.buffer.length > 0, "Buffer should not be empty");
    }
  });

  it("should generate and save to file", async () => {
    const outputPath = path.join(tempDir, "test-output.docx");
    const result = await service.generateToFile(
      {
        title: "File Output Test",
        paragraphs: [
          { text: "This file was generated by DocxService.", heading: "Heading1" },
          { text: "It should be saved to disk." },
        ],
      },
      outputPath,
    );

    assert.ok(result.ok, "Generate to file should succeed");
    if (result.ok) {
      assert.equal(result.value.filePath, outputPath, "File path should match");
      assert.ok(result.value.size > 0, "Size should be positive");

      // Verify file exists on disk
      const stat = await fs.stat(outputPath);
      assert.ok(stat.size > 0, "File should exist on disk with content");
    }
  });

  it("should create parent directories when saving", async () => {
    const outputPath = path.join(tempDir, "nested", "dir", "output.docx");
    const result = await service.generateToFile(
      {
        paragraphs: [{ text: "Nested directory test" }],
      },
      outputPath,
    );

    assert.ok(result.ok, "Generate to nested path should succeed");
    if (result.ok) {
      const stat = await fs.stat(outputPath);
      assert.ok(stat.size > 0, "File should exist in nested directory");
    }
  });

  it("should generate with multiple tables", async () => {
    const result = await service.generate({
      paragraphs: [{ text: "Multi-table Report", heading: "Heading1" }],
      tables: [
        {
          rows: [["A", "B"], ["1", "2"]],
          headerRow: true,
        },
        {
          rows: [["C", "D"], ["3", "4"]],
          headerRow: true,
        },
      ],
    });

    assert.ok(result.ok, "Generate with multiple tables should succeed");
    if (result.ok) {
      assert.ok(result.value.buffer.length > 0, "Buffer should not be empty");
    }
  });

  it("should generate with column widths", async () => {
    const result = await service.generate({
      paragraphs: [{ text: "Column Width Test", heading: "Heading1" }],
      tables: [
        {
          rows: [
            ["Name", "Value", "Description"],
            ["Item A", "100", "First item"],
            ["Item B", "200", "Second item"],
          ],
          headerRow: true,
          columnWidths: [30, 20, 50],
        },
      ],
    });

    assert.ok(result.ok, "Generate with column widths should succeed");
  });

  it("should generate with creator and description metadata", async () => {
    const result = await service.generate({
      title: "Metadata Test",
      paragraphs: [{ text: "Document with metadata." }],
      creator: "Test Suite",
      description: "A test document with metadata",
    });

    assert.ok(result.ok, "Generate with metadata should succeed");
  });
});

describe("DocxService — parse", () => {
  it("should parse a generated .docx file", async () => {
    // First generate a document
    const genResult = await service.generate({
      title: "Parse Test",
      paragraphs: [
        { text: "Revenue Report", heading: "Heading1" },
        { text: "Total revenue: ¥1,234,567" },
        { text: "Net profit: ¥246,913" },
      ],
    });
    assert.ok(genResult.ok, "Generate should succeed for parse test");

    if (genResult.ok) {
      // Now parse it
      const parseResult = await service.parse(genResult.value.buffer);
      assert.ok(parseResult.ok, "Parse should succeed");
      if (parseResult.ok) {
        assert.ok(parseResult.value.text.length > 0, "Extracted text should not be empty");
        assert.ok(parseResult.value.charCount > 0, "Character count should be positive");
        assert.ok(
          parseResult.value.text.includes("Revenue Report") ||
          parseResult.value.text.includes("revenue") ||
          parseResult.value.text.includes("Parse Test"),
          "Extracted text should contain document content",
        );
      }
    }
  });

  it("should parse a .docx file from disk", async () => {
    // Generate and save
    const filePath = path.join(tempDir, "parse-test.docx");
    await service.generateToFile(
      {
        title: "File Parse Test",
        paragraphs: [
          { text: "This is a test document for file parsing." },
          { text: "It contains multiple paragraphs." },
        ],
      },
      filePath,
    );

    // Parse from file
    const result = await service.parseFile(filePath);
    assert.ok(result.ok, "Parse file should succeed");
    if (result.ok) {
      assert.ok(result.value.text.length > 0, "Extracted text should not be empty");
    }
  });

  it("should return error for non-existent file", async () => {
    const result = await service.parseFile(path.join(tempDir, "nonexistent.docx"));
    assert.ok(!result.ok, "Parse non-existent file should fail");
    if (!result.ok) {
      assert.ok(result.error.includes("Failed to read file"), "Error should mention file read failure");
    }
  });

  it("should return error for invalid buffer", async () => {
    const result = await service.parse(Buffer.from("not a docx file"));
    assert.ok(!result.ok, "Parse invalid buffer should fail");
    if (!result.ok) {
      assert.ok(result.error.includes("Failed to parse"), "Error should mention parse failure");
    }
  });
});

describe("DocxService — round-trip", () => {
  it("should generate → parse → verify content", async () => {
    const originalContent = {
      title: "Round-Trip Test",
      paragraphs: [
        { text: "Financial Summary", heading: "Heading1" as const },
        { text: "Total Revenue: ¥4,484,567" },
        { text: "Total Cost: ¥3,287,654" },
        { text: "Net Profit: ¥1,196,913" },
      ],
      tables: [
        {
          rows: [
            ["Quarter", "Revenue", "Cost", "Net"],
            ["Q1", "1,234,567", "987,654", "246,913"],
            ["Q2", "1,500,000", "1,100,000", "400,000"],
            ["Q3", "1,750,000", "1,200,000", "550,000"],
          ],
          headerRow: true,
        },
      ],
    };

    // Generate
    const genResult = await service.generate(originalContent);
    assert.ok(genResult.ok, "Generate should succeed");

    if (genResult.ok) {
      // Parse
      const parseResult = await service.parse(genResult.value.buffer);
      assert.ok(parseResult.ok, "Parse should succeed");

      if (parseResult.ok) {
        const text = parseResult.value.text;
        // Verify key content is present in extracted text
        assert.ok(text.includes("Round-Trip Test") || text.includes("Financial Summary"), "Title or heading should be in text");
        assert.ok(text.includes("4,484,567") || text.includes("Revenue"), "Revenue should be in text");
      }
    }
  });
});

describe("DocxTool", () => {
  it("should generate a .docx file via tool", async () => {
    const outputPath = path.join(tempDir, "tool-generate.docx");
    const result = await tool.execute({
      operation: "generate",
      filePath: outputPath,
      title: "Tool Generated Report",
      paragraphs: [
        { text: "Executive Summary", heading: "Heading1" },
        { text: "This report was generated by the DocxTool." },
        { text: "It demonstrates the tool interface." },
      ],
      tables: [
        {
          rows: [
            ["Metric", "Value"],
            ["Revenue", "¥1,234,567"],
            ["Growth", "15.3%"],
          ],
          headerRow: true,
        },
      ],
    });

    assert.ok(result.success, "Tool generate should succeed");
    assert.equal(result.operation, "generate");
    assert.ok(result.filePath, "File path should be set");
    assert.ok(result.size! > 0, "Size should be positive");

    // Verify file exists
    const stat = await fs.stat(outputPath);
    assert.ok(stat.size > 0, "File should exist on disk");
  });

  it("should parse a .docx file via tool", async () => {
    // First generate
    const filePath = path.join(tempDir, "tool-parse.docx");
    await tool.execute({
      operation: "generate",
      filePath,
      title: "Parse Test Document",
      paragraphs: [
        { text: "This document will be parsed." },
        { text: "It contains text for extraction." },
      ],
    });

    // Now parse
    const result = await tool.execute({
      operation: "parse",
      filePath,
    });

    assert.ok(result.success, "Tool parse should succeed");
    assert.equal(result.operation, "parse");
    assert.ok(result.text!.length > 0, "Extracted text should not be empty");
    assert.ok(result.charCount! > 0, "Character count should be positive");
  });

  it("should fail when generating without paragraphs or tables", async () => {
    const result = await tool.execute({
      operation: "generate",
      filePath: path.join(tempDir, "empty.docx"),
    });

    assert.ok(!result.success, "Should fail without content");
    assert.ok(result.message.includes("paragraph or table"), "Error should mention missing content");
  });

  it("should fail when parsing non-existent file", async () => {
    const result = await tool.execute({
      operation: "parse",
      filePath: path.join(tempDir, "does-not-exist.docx"),
    });

    assert.ok(!result.success, "Should fail for non-existent file");
    assert.ok(result.message.includes("Failed"), "Error should mention failure");
  });

  it("should fail for unknown operation", async () => {
    const result = await tool.execute({
      operation: "unknown" as "parse",
      filePath: "test.docx",
    });

    assert.ok(!result.success, "Should fail for unknown operation");
    assert.ok(result.message.includes("Unknown operation"), "Error should mention unknown operation");
  });

  it("should fail when filePath is empty for parse", async () => {
    const result = await tool.execute({
      operation: "parse",
      filePath: "",
    });

    assert.ok(!result.success, "Should fail with empty filePath");
    assert.ok(result.message.includes("required"), "Error should mention required");
  });

  it("should generate with only tables (no paragraphs)", async () => {
    const result = await tool.execute({
      operation: "generate",
      filePath: path.join(tempDir, "tables-only.docx"),
      tables: [
        {
          rows: [
            ["Name", "Value"],
            ["A", "1"],
            ["B", "2"],
          ],
          headerRow: true,
        },
      ],
    });

    assert.ok(result.success, "Should succeed with only tables");
  });
});
